<form method="post" action="<?= $this->url('standardPayment', array(
                    'controller' => 'indext',
                    'action'     => 'pay',
            )) ?>">
    <fieldset>
    	<legend>Order :</legend>
        <div class="form-group">
            <label for="price-input">Price</label>
            <input name="price" class="form-control" id="price-input" placeholder="Tatal price" required>
        </div>
        <div class="form-group">
            <label for="currency-input">Currency</label>
            <select name="currency" class="form-control" id="currency-input">
                <option value="USD">USD</option>
                <option value="EUR">EUR</option>
                <option value="THB">THB</option>
                <option value="HKD">HKD</option>
                <option value="SGD">SGD</option>
                <option value="AUD">AUD</option>
            </select>
        </div>
        <div class="form-group">
            <label for="full-name">Full name</label>
            <input class="form-control" type="text" id="full-name" placeholder="Firstname" required>
        </div>
    </fieldset>
    <fieldset>
    	<legend>Credit card :</legend>
    	<div class="form-group">
            <label for="holdername-input">Holder name</label>
            <input name="firstname" class="form-control" id="holdername-input" placeholder="Firstname" required>
            <input name="lastname" class="form-control" id="holdername-input" placeholder="Lastname" required>
            </div>
        <div class="form-group">
            <label for="number-input">Number</label>
            <input name="number" class="form-control" id="number-input" placeholder="Credit car number" required>
        </div>
        <div class="form-group">
            <label for="expiration-input">Expiration</label>
            <select name="expiredMonth" id="currency-input">
            <?php for ($i=1; $i<=12; $i++) : ?>
                <option value="<?php printf("%02d", $i)?>"><?php printf("%02d", $i)?></option>
            <?php endfor;?>
            </select>
            <select name="expiredYear" id="currency-input">
            <?php for ($i=14; $i<=30; $i++) : ?>
                <option value="<?php printf("%02d", $i)?>">20<?php printf("%02d", $i)?></option>
            <?php endfor;?>
            </select>
        </div>
        <div class="form-group">
            <label for="ccv-input">CCV</label>
            <input class="form-control" id="ccv-input" placeholder="3 digit of ccv" required>
        </div>
	</fieldset>
	<button type="submit" class="btn btn-default">Checkout</button>
</form>